import React, { useState, useEffect } from 'react';
import { Download, Github, Check, AlertCircle, Loader2, ExternalLink, Shield, Globe, X, Settings as SettingsIcon } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { doc, getDoc } from 'firebase/firestore';
import { db, auth } from '../firebase';
import { handleFirestoreError, OperationType } from '../utils/firestoreErrorHandler';
import { UserSettings } from '../types';

interface ExportManagerProps {
  artifacts: Record<string, string>;
  projectName: string;
  onDownloadZip: () => void;
  onGoToSettings: () => void;
}

export const ExportManager: React.FC<ExportManagerProps> = ({ artifacts, projectName, onDownloadZip, onGoToSettings }) => {
  const [exportType, setExportType] = useState<'zip' | 'github'>('zip');
  const [githubToken, setGithubToken] = useState<string | null>(localStorage.getItem('github_token'));
  const [isExporting, setIsExporting] = useState(false);
  const [exportStatus, setExportStatus] = useState<{ type: 'success' | 'error', message: string, url?: string } | null>(null);
  const [userSettings, setUserSettings] = useState<UserSettings | null>(null);
  const [loadingSettings, setLoadingSettings] = useState(true);
  
  // GitHub Repo Config
  const [repoName, setRepoName] = useState(projectName.replace(/\s+/g, '-').toLowerCase());
  const [repoDescription, setRepoDescription] = useState(`Project generated by MultiAgent Lab: ${projectName}`);
  const [isPrivate, setIsPrivate] = useState(false);

  useEffect(() => {
    const fetchSettings = async () => {
      if (!auth.currentUser) return;
      try {
        const docRef = doc(db, 'users', auth.currentUser.uid, 'settings', 'integrations');
        const docSnap = await getDoc(docRef);
        if (docSnap.exists()) {
          setUserSettings(docSnap.data() as UserSettings);
        }
      } catch (err) {
        handleFirestoreError(err, OperationType.GET, `users/${auth.currentUser.uid}/settings/integrations`);
      } finally {
        setLoadingSettings(false);
      }
    };

    fetchSettings();

    const handleMessage = (event: MessageEvent) => {
      if (event.data?.type === 'GITHUB_AUTH_SUCCESS') {
        const token = event.data.token;
        setGithubToken(token);
        localStorage.setItem('github_token', token);
      }
    };
    window.addEventListener('message', handleMessage);
    return () => window.removeEventListener('message', handleMessage);
  }, []);

  const handleGithubConnect = async () => {
    try {
      let url = '/api/auth/github/url';
      if (userSettings?.githubClientId && userSettings?.githubClientSecret) {
        const params = new URLSearchParams({
          clientId: userSettings.githubClientId,
          clientSecret: userSettings.githubClientSecret
        });
        url += `?${params.toString()}`;
      }
      const res = await fetch(url);
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      window.open(data.url, 'github_auth', 'width=600,height=700');
    } catch (err: any) {
      console.error("Auth error:", err);
      setExportStatus({ type: 'error', message: `Error de autenticación: ${err.message}` });
    }
  };

  const handleGithubExport = async () => {
    if (!githubToken) return;
    setIsExporting(true);
    setExportStatus(null);

    try {
      const res = await fetch('/api/export/github', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          token: githubToken,
          repoName,
          description: repoDescription,
          artifacts,
          isPrivate
        })
      });

      const data = await res.json();
      if (data.success) {
        setExportStatus({ type: 'success', message: '¡Proyecto exportado exitosamente a GitHub!', url: data.url });
      } else {
        throw new Error(data.error || 'Error al exportar a GitHub');
      }
    } catch (err: any) {
      setExportStatus({ type: 'error', message: err.message });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="h-full flex flex-col bg-black/40 rounded-[2rem] border border-white/5 overflow-hidden">
      <div className="p-8 border-b border-white/5 bg-white/[0.02]">
        <h3 className="text-2xl font-bold text-white mb-2">Exportar Proyecto</h3>
        <p className="text-sm text-neutral-500">Lleva tu código al siguiente nivel exportándolo a tu entorno preferido.</p>
      </div>

      <div className="flex-1 p-8 overflow-y-auto custom-scrollbar">
        <div className="max-w-2xl mx-auto space-y-8">
          {/* Export Type Selection */}
          <div className="grid grid-cols-2 gap-4">
            <button 
              onClick={() => setExportType('zip')}
              className={`p-6 rounded-2xl border transition-all text-left flex flex-col gap-4 ${
                exportType === 'zip' ? 'bg-white/10 border-white/20' : 'bg-white/[0.02] border-white/5 hover:bg-white/[0.05]'
              }`}
            >
              <div className={`size-12 rounded-xl flex items-center justify-center ${exportType === 'zip' ? 'bg-white text-black' : 'bg-white/5 text-white'}`}>
                <Download size={24} />
              </div>
              <div>
                <h4 className="font-bold text-white">Archivo ZIP</h4>
                <p className="text-xs text-neutral-500 mt-1">Descarga local de todos los artefactos.</p>
              </div>
            </button>

            <button 
              onClick={() => setExportType('github')}
              className={`p-6 rounded-2xl border transition-all text-left flex flex-col gap-4 ${
                exportType === 'github' ? 'bg-emerald-500/10 border-emerald-500/20' : 'bg-white/[0.02] border-white/5 hover:bg-white/[0.05]'
              }`}
            >
              <div className={`size-12 rounded-xl flex items-center justify-center ${exportType === 'github' ? 'bg-emerald-500 text-black' : 'bg-white/5 text-white'}`}>
                <Github size={24} />
              </div>
              <div>
                <h4 className="font-bold text-white">GitHub Repo</h4>
                <p className="text-xs text-neutral-500 mt-1">Crea un repositorio y sube el código directamente.</p>
              </div>
            </button>
          </div>

          <AnimatePresence mode="wait">
            {exportType === 'zip' ? (
              <motion.div 
                key="zip"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="bg-white/[0.02] border border-white/5 rounded-3xl p-8 text-center space-y-6"
              >
                <div className="size-20 bg-white/5 rounded-full flex items-center justify-center mx-auto">
                  <Download size={32} className="text-neutral-400" />
                </div>
                <div>
                  <h5 className="text-lg font-bold text-white">Listo para descargar</h5>
                  <p className="text-sm text-neutral-500 mt-2">Se generará un archivo .zip con {Object.keys(artifacts).length} archivos y un README.md descriptivo.</p>
                </div>
                <button 
                  onClick={onDownloadZip}
                  className="w-full py-4 bg-white text-black rounded-xl font-bold hover:bg-neutral-200 transition-all flex items-center justify-center gap-2"
                >
                  <Download size={18} />
                  Descargar ZIP
                </button>
              </motion.div>
            ) : (
              <motion.div 
                key="github"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                className="space-y-6"
              >
                {!githubToken ? (
                  <div className="bg-emerald-500/5 border border-emerald-500/10 rounded-3xl p-12 text-center space-y-6">
                    <div className="size-20 bg-emerald-500/10 rounded-full flex items-center justify-center mx-auto text-emerald-500">
                      <Github size={40} />
                    </div>
                    <div>
                      <h5 className="text-xl font-bold text-white">Conecta tu cuenta de GitHub</h5>
                      <p className="text-sm text-neutral-500 mt-2">Necesitamos permisos para crear repositorios en tu nombre.</p>
                      
                      {(!userSettings?.githubClientId || !userSettings?.githubClientSecret) && (
                        <div className="mt-4 p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl text-left">
                          <div className="flex items-start gap-3">
                            <AlertCircle size={18} className="text-amber-500 shrink-0 mt-0.5" />
                            <div>
                              <p className="text-xs font-bold text-amber-500 uppercase tracking-wider">Configuración Requerida</p>
                              <p className="text-[11px] text-neutral-400 mt-1">
                                Para usar tu propia aplicación de GitHub, primero debes configurar las credenciales en la sección de Ajustes.
                              </p>
                              <button 
                                onClick={onGoToSettings}
                                className="mt-2 text-[11px] font-bold text-white flex items-center gap-1 hover:underline"
                              >
                                <SettingsIcon size={12} />
                                Ir a Ajustes
                              </button>
                            </div>
                          </div>
                        </div>
                      )}
                    </div>
                    <button 
                      onClick={handleGithubConnect}
                      className="px-8 py-4 bg-emerald-500 text-black rounded-xl font-bold hover:bg-emerald-600 transition-all flex items-center justify-center gap-2 mx-auto"
                    >
                      <Github size={18} />
                      Conectar con GitHub
                    </button>
                  </div>
                ) : (
                  <div className="bg-white/[0.02] border border-white/5 rounded-3xl p-8 space-y-6">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="size-10 bg-emerald-500/10 rounded-lg flex items-center justify-center text-emerald-500">
                          <Github size={20} />
                        </div>
                        <div>
                          <p className="text-[10px] text-neutral-500 uppercase tracking-widest font-black">Conectado como</p>
                          <p className="text-xs text-white font-bold">GitHub User</p>
                        </div>
                      </div>
                      <button 
                        onClick={() => { setGithubToken(null); localStorage.removeItem('github_token'); }}
                        className="text-[10px] text-rose-500 hover:underline font-bold"
                      >
                        Desconectar
                      </button>
                    </div>

                    <div className="space-y-4">
                      <div>
                        <label className="text-[10px] text-neutral-500 uppercase tracking-widest font-black block mb-2">Nombre del Repositorio</label>
                        <input 
                          type="text" 
                          value={repoName}
                          onChange={(e) => setRepoName(e.target.value)}
                          className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:border-emerald-500 outline-none transition-all"
                          placeholder="nombre-del-repo"
                        />
                      </div>
                      <div>
                        <label className="text-[10px] text-neutral-500 uppercase tracking-widest font-black block mb-2">Descripción</label>
                        <textarea 
                          value={repoDescription}
                          onChange={(e) => setRepoDescription(e.target.value)}
                          className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 text-sm text-white focus:border-emerald-500 outline-none transition-all h-24 resize-none"
                          placeholder="Descripción del proyecto..."
                        />
                      </div>
                      <div className="flex items-center justify-between p-4 bg-black/20 rounded-xl border border-white/5">
                        <div className="flex items-center gap-3">
                          {isPrivate ? <Shield size={18} className="text-amber-500" /> : <Globe size={18} className="text-emerald-500" />}
                          <div>
                            <p className="text-xs font-bold text-white">{isPrivate ? 'Repositorio Privado' : 'Repositorio Público'}</p>
                            <p className="text-[10px] text-neutral-500">Solo tú podrás ver este código.</p>
                          </div>
                        </div>
                        <button 
                          onClick={() => setIsPrivate(!isPrivate)}
                          className={`w-12 h-6 rounded-full transition-all relative ${isPrivate ? 'bg-emerald-500' : 'bg-white/10'}`}
                        >
                          <div className={`absolute top-1 size-4 rounded-full bg-white transition-all ${isPrivate ? 'right-1' : 'left-1'}`} />
                        </button>
                      </div>
                    </div>

                    <button 
                      disabled={isExporting}
                      onClick={handleGithubExport}
                      className="w-full py-4 bg-emerald-500 text-black rounded-xl font-bold hover:bg-emerald-600 transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {isExporting ? <Loader2 size={18} className="animate-spin" /> : <Github size={18} />}
                      {isExporting ? 'Exportando...' : 'Crear Repo y Exportar'}
                    </button>
                  </div>
                )}
              </motion.div>
            )}
          </AnimatePresence>

          {/* Status Messages */}
          <AnimatePresence>
            {exportStatus && (
              <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className={`p-6 rounded-2xl border flex items-start gap-4 ${
                  exportStatus.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : 'bg-rose-500/10 border-rose-500/20 text-rose-400'
                }`}
              >
                <div className="mt-1">
                  {exportStatus.type === 'success' ? <Check size={20} /> : <AlertCircle size={20} />}
                </div>
                <div className="flex-1">
                  <p className="text-sm font-bold">{exportStatus.message}</p>
                  {exportStatus.url && (
                    <div className="mt-4 space-y-4">
                      <a 
                        href={exportStatus.url} 
                        target="_blank" 
                        rel="noopener noreferrer"
                        className="inline-flex items-center gap-2 text-xs font-black uppercase tracking-widest hover:underline"
                      >
                        Ver en GitHub
                        <ExternalLink size={12} />
                      </a>
                      
                      <div className="p-4 bg-black/40 rounded-xl border border-white/5 space-y-2">
                        <p className="text-[10px] font-black uppercase tracking-widest text-neutral-500">Comando para clonar:</p>
                        <div className="flex items-center justify-between gap-4 bg-black/60 p-3 rounded-lg border border-white/10">
                          <code className="text-xs text-emerald-400 font-mono break-all">
                            git clone {exportStatus.url}.git
                          </code>
                          <button 
                            onClick={() => {
                              navigator.clipboard.writeText(`git clone ${exportStatus.url}.git`);
                            }}
                            className="p-2 hover:bg-white/10 rounded-md transition-colors text-neutral-400 hover:text-white"
                            title="Copiar comando"
                          >
                            <Download size={14} />
                          </button>
                        </div>
                        <p className="text-[8px] text-neutral-600 italic">
                          Ejecuta este comando en tu terminal (CMD) para descargar el proyecto localmente.
                        </p>
                      </div>
                    </div>
                  )}
                </div>
                <button onClick={() => setExportStatus(null)} className="text-neutral-500 hover:text-white">
                  <X size={16} />
                </button>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
};
